FROM rust:1.81-slim-bookworm

WORKDIR /app

# Install dependencies
RUN apt-get update && apt-get install -y \
    pkg-config \
    libssl-dev \
    && rm -rf /var/lib/apt/lists/*

# Copy everything
COPY . .

# Build and run the application
CMD ["cargo", "run"]