services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        FEATURES: ""  # Set to "sentry-monitoring" to enable Sentry
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      - RUST_LOG=info
      # Set this in production and add to .env
      # - ENVIRONMENT=production
      # - SENTRY_DSN=your_sentry_dsn
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s

  # Development service for local development
  dev:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder
    volumes:
      - .:/app
      - cargo-cache:/usr/local/cargo/registry
      - meeting-data:/app/data
    ports:
      - "13000:3000"
    env_file:
      - .env
    environment:
      - RUST_LOG=debug
      - RUST_BACKTRACE=1
    command: bash -c "cargo install cargo-watch && cargo watch -w src -x run"

volumes:
  cargo-cache:
  meeting-data: